sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t mok/docker-react-app -f dockerfile.dev .

script:
  - docker run -e CI=true mok/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"
